language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install --upgrade pip
  - pip install -U -r requirements.txt -r requirements-dev.txt
script:
  - python -m pytest
